import type { AchievementDefinition } from "@/lib/types";

/** Canonical catalog mirrored by the Lua addon + Supabase seed. */
export const ACHIEVEMENT_CATALOG: AchievementDefinition[] = [
  {
    id: "1001",
    name: "Fresh Meat",
    description: "Create a character and take your first steps into Azeroth. Reach level 2.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Nature_Regeneration",
  },
  {
    id: "1002",
    name: "Out of the Nest",
    description: "Reach level 5.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_BattleShout",
  },
  {
    id: "1003",
    name: "Double Digits",
    description: "Reach level 10.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Nature_Strength",
  },
  {
    id: "1004",
    name: "Getting Dangerous",
    description: "Reach level 20.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_DualWield",
  },
  {
    id: "1005",
    name: "Halfway Hero",
    description: "Reach level 30.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfMight",
  },
  {
    id: "1006",
    name: "Seasoned Adventurer",
    description: "Reach level 40.",
    category: "General",
    points: 15,
    icon: "Interface\\\\Icons\\\\Ability_TownWatch",
  },
  {
    id: "1007",
    name: "Elite Contender",
    description: "Reach level 50.",
    category: "General",
    points: 20,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfWisdom",
  },
  {
    id: "1008",
    name: "The Climb",
    description: "Reach level 55.",
    category: "General",
    points: 20,
    icon: "Interface\\\\Icons\\\\Spell_Nature_EarthBind",
  },
  {
    id: "1009",
    name: "Ready for Anything",
    description: "Reach level 58 — the gates of endgame beckon.",
    category: "General",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_01",
  },
  {
    id: "1010",
    name: "Well-Rested",
    description: "Log in to Azeroth. Welcome back, hero.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfWisdom",
  },
  {
    id: "1011",
    name: "For the Alliance!",
    description: "Create an Alliance character.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_BannerPVP_02",
  },
  {
    id: "1012",
    name: "For the Horde!",
    description: "Create a Horde character.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_BannerPVP_01",
  },
  {
    id: "1013",
    name: "Lionheart",
    description: "Create a Human.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Holy_HolyBolt",
  },
  {
    id: "1014",
    name: "By Hammer and Anvil",
    description: "Create a Dwarf.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Drink_04",
  },
  {
    id: "1015",
    name: "Child of the Stars",
    description: "Create a Night Elf.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Ambush",
  },
  {
    id: "1016",
    name: "Gnomish Ingenuity",
    description: "Create a Gnome.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Gizmo_01",
  },
  {
    id: "1017",
    name: "Lok'tar Ogar",
    description: "Create an Orc.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_WarCry",
  },
  {
    id: "1018",
    name: "Death Becomes You",
    description: "Create an Undead.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_RaiseDead",
  },
  {
    id: "1019",
    name: "Walks with the Earthmother",
    description: "Create a Tauren.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Nature_HealingTouch",
  },
  {
    id: "1020",
    name: "Voodoo Shuffle",
    description: "Create a Troll.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_ShadowWordPain",
  },
  {
    id: "1021",
    name: "Arms Wide Open",
    description: "Play as a Warrior.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Sword_27",
  },
  {
    id: "1022",
    name: "Light's Favored",
    description: "Play as a Paladin.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfMight",
  },
  {
    id: "1023",
    name: "Hunter's Path",
    description: "Play as a Hunter.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Hunter_RunningShot",
  },
  {
    id: "1024",
    name: "Shadow Dance",
    description: "Play as a Rogue.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Stealth",
  },
  {
    id: "1025",
    name: "Faithful Servant",
    description: "Play as a Priest.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Holy_PowerWordShield",
  },
  {
    id: "1026",
    name: "Elemental Affinity",
    description: "Play as a Shaman.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Nature_BloodLust",
  },
  {
    id: "1027",
    name: "Arcane Ambition",
    description: "Play as a Mage.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Frost_IceStorm",
  },
  {
    id: "1028",
    name: "Pact Maker",
    description: "Play as a Warlock.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_ShadowBolt",
  },
  {
    id: "1029",
    name: "Wild Shape of Mind",
    description: "Play as a Druid.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Nature_HealingTouch",
  },
  {
    id: "1030",
    name: "Social Butterfly",
    description: "/wave, /dance, or otherwise emote 25 times.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_Charm",
  },
  {
    id: "1031",
    name: "Party Starter",
    description: "Dance it out — use a /dance emote.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Holy_HolyBolt",
  },
  {
    id: "1032",
    name: "Achievement Addict",
    description: "Earn 25 achievements.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Jewelry_Talisman_08",
  },
  {
    id: "1033",
    name: "Overachiever",
    description: "Earn 50 achievements.",
    category: "General",
    points: 20,
    icon: "Interface\\\\Icons\\\\INV_Jewelry_Talisman_08",
  },
  {
    id: "1034",
    name: "Completionist Tendencies",
    description: "Earn 100 achievements.",
    category: "General",
    points: 50,
    icon: "Interface\\\\Icons\\\\INV_Jewelry_Talisman_08",
  },
  {
    id: "1035",
    name: "Friendly Face",
    description: "Become Friendly with Stormwind.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_GroupLooking",
  },
  {
    id: "1036",
    name: "Honored Guest",
    description: "Become Honored with Stormwind.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_GroupLooking",
  },
  {
    id: "1037",
    name: "Lok'tar Reputation",
    description: "Become Friendly with Orgrimmar.",
    category: "General",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_GroupLooking",
  },
  {
    id: "1038",
    name: "Orgrimmar Honored",
    description: "Become Honored with Orgrimmar.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_GroupLooking",
  },
  {
    id: "1039",
    name: "Argent Dawn Ally",
    description: "Become Friendly with the Argent Dawn.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Jewelry_Talisman_07",
  },
  {
    id: "1040",
    name: "Timbermaw Friend",
    description: "Become Friendly with Timbermaw Hold.",
    category: "General",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_MonsterClaw_04",
  },
  {
    id: "2001",
    name: "Permadeath Protocol",
    description: "Log in on a Hardcore character.",
    category: "Hardcore",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_DefensiveStance",
  },
  {
    id: "2002",
    name: "Still Breathing",
    description: "Reach level 10 without dying on Hardcore.",
    category: "Hardcore",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfProtection",
  },
  {
    id: "2003",
    name: "Greenhorn Survivor",
    description: "Reach level 20 without dying on Hardcore.",
    category: "Hardcore",
    points: 15,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_DefensiveStance",
  },
  {
    id: "2004",
    name: "Hardened",
    description: "Reach level 30 without dying on Hardcore.",
    category: "Hardcore",
    points: 20,
    icon: "Interface\\\\Icons\\\\INV_Shield_06",
  },
  {
    id: "2005",
    name: "Iron Will",
    description: "Reach level 40 without dying on Hardcore.",
    category: "Hardcore",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Shield_05",
  },
  {
    id: "2006",
    name: "Unbreakable",
    description: "Reach level 50 without dying on Hardcore.",
    category: "Hardcore",
    points: 35,
    icon: "Interface\\\\Icons\\\\INV_Shield_04",
  },
  {
    id: "2007",
    name: "Immortal Contender",
    description: "Reach level 60 without dying on Hardcore.",
    category: "Hardcore",
    points: 50,
    icon: "Interface\\\\Icons\\\\Spell_Holy_HolyBolt",
  },
  {
    id: "2008",
    name: "Sweaty Palms",
    description: "On Hardcore, survive combat after dropping to 5% health.",
    category: "Hardcore",
    points: 15,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_LifeDrain",
  },
  {
    id: "2009",
    name: "Heart Attack Simulator",
    description: "On Hardcore, survive combat after dropping to 1% health.",
    category: "Hardcore",
    points: 25,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfSacrifice",
  },
  {
    id: "2010",
    name: "Cautious Adventurer",
    description: "On Hardcore, complete 50 quests without dying.",
    category: "Hardcore",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Note_02",
  },
  {
    id: "2011",
    name: "Self-Sufficient",
    description: "On Hardcore, reach 150 skill in any gathering profession.",
    category: "Hardcore",
    points: 10,
    icon: "Interface\\\\Icons\\\\Trade_Mining",
  },
  {
    id: "2012",
    name: "Dungeon? On Hardcore?",
    description: "Enter a dungeon on a Hardcore character. Bold strategy.",
    category: "Hardcore",
    points: 20,
    icon: "Interface\\\\Icons\\\\INV_Misc_Key_11",
  },
  {
    id: "2013",
    name: "Death's Door",
    description: "Die once. (Not recommended on Hardcore.)",
    category: "Hardcore",
    points: 0,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_DeathCoil",
  },
  {
    id: "2014",
    name: "Frequent Flyer",
    description: "Die 10 times. The spirit healer knows your name.",
    category: "Hardcore",
    points: 0,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_Twilight",
  },
  {
    id: "3001",
    name: "Tourist",
    description: "Visit 5 different zones.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_TownWatch",
  },
  {
    id: "3002",
    name: "Wanderer",
    description: "Visit 10 different zones.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Tracking",
  },
  {
    id: "3003",
    name: "Globe-Trotter",
    description: "Visit 20 different zones.",
    category: "Exploration",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3004",
    name: "Cartographer",
    description: "Visit 35 different zones.",
    category: "Exploration",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3005",
    name: "Elwynn Bound",
    description: "Visit Elwynn Forest.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3006",
    name: "Westfall Bound",
    description: "Visit Westfall.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3007",
    name: "Redridge Bound",
    description: "Visit Redridge Mountains.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3008",
    name: "Duskwood Bound",
    description: "Visit Duskwood.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_Twilight",
  },
  {
    id: "3009",
    name: "Into the Jungle",
    description: "Visit Stranglethorn Vale.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Hunter_RunningShot",
  },
  {
    id: "3010",
    name: "Durotar Bound",
    description: "Visit Durotar.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3011",
    name: "Barrens Chat",
    description: "Visit The Barrens. May the chat forgive you.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3012",
    name: "Mulgore Bound",
    description: "Visit Mulgore.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3013",
    name: "Ashenvale Bound",
    description: "Visit Ashenvale.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Nature_ProtectionForm",
  },
  {
    id: "3014",
    name: "Wetlands Bound",
    description: "Visit the Wetlands.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Frost_SummonWaterElemental",
  },
  {
    id: "3015",
    name: "Hillsbrad Bound",
    description: "Visit Hillsbrad Foothills.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3016",
    name: "Tanaris Bound",
    description: "Visit Tanaris.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Dust_02",
  },
  {
    id: "3017",
    name: "Un'Goro Bound",
    description: "Visit Un'Goro Crater.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_01",
  },
  {
    id: "3018",
    name: "Winterspring Bound",
    description: "Visit Winterspring.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Frost_FrostBolt02",
  },
  {
    id: "3019",
    name: "Blasted Lands Bound",
    description: "Visit the Blasted Lands.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Fire_Volcano",
  },
  {
    id: "3020",
    name: "City Slicker: Stormwind",
    description: "Visit Stormwind City.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Arcane_TeleportStormWind",
  },
  {
    id: "3021",
    name: "City Slicker: Orgrimmar",
    description: "Visit Orgrimmar.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Arcane_TeleportOrgrimmar",
  },
  {
    id: "3022",
    name: "City Slicker: Ironforge",
    description: "Visit Ironforge.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Arcane_TeleportIronForge",
  },
  {
    id: "3023",
    name: "City Slicker: Undercity",
    description: "Visit Undercity.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Arcane_TeleportUnderCity",
  },
  {
    id: "3024",
    name: "City Slicker: Thunder Bluff",
    description: "Visit Thunder Bluff.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Arcane_TeleportThunderBluff",
  },
  {
    id: "3025",
    name: "City Slicker: Darnassus",
    description: "Visit Darnassus.",
    category: "Exploration",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Arcane_TeleportDarnassus",
  },
  {
    id: "3026",
    name: "Eastern Kingdoms Sampler",
    description: "Visit Elwynn Forest, Westfall, and Redridge Mountains.",
    category: "Exploration",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3027",
    name: "Kalimdor Sampler",
    description: "Visit Durotar, The Barrens, and Mulgore.",
    category: "Exploration",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3028",
    name: "Blackrock Bound",
    description: "Visit Burning Steppes or Searing Gorge.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Fire_Volcano",
  },
  {
    id: "3029",
    name: "Hinterlands Bound",
    description: "Visit The Hinterlands.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "3030",
    name: "Silithus Bound",
    description: "Visit Silithus.",
    category: "Exploration",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Gem_Stone_01",
  },
  {
    id: "4001",
    name: "First Blood",
    description: "Slay your first creature.",
    category: "Combat",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_DualWield",
  },
  {
    id: "4002",
    name: "Blooded",
    description: "Slay 50 creatures.",
    category: "Combat",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_SavageBlow",
  },
  {
    id: "4003",
    name: "Exterminator",
    description: "Slay 250 creatures.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_Rampage",
  },
  {
    id: "4004",
    name: "Grim Reaper",
    description: "Slay 1,000 creatures.",
    category: "Combat",
    points: 15,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_DeathPact",
  },
  {
    id: "4005",
    name: "Walking Apocalypse",
    description: "Slay 5,000 creatures.",
    category: "Combat",
    points: 25,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_AnimateDead",
  },
  {
    id: "4006",
    name: "Murloc Massacre",
    description: "Slay 100 murlocs. Somebody has to do it.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_MonsterHead_02",
  },
  {
    id: "4007",
    name: "Gnoll Problem",
    description: "Slay 50 gnolls.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Gnoll_01",
  },
  {
    id: "4008",
    name: "Kobold Clearance",
    description: "Slay 50 kobolds. You no take candle!",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Candle_02",
  },
  {
    id: "4009",
    name: "Defias Buster",
    description: "Slay 50 Defias.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Rogue_Disguise",
  },
  {
    id: "4010",
    name: "Scourge of the Scourge",
    description: "Slay 100 undead (name contains \"undead\", \"skeleton\", \"ghoul\", or \"zombie\"). Slay 100 skeletons.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_RaiseDead",
  },
  {
    id: "4011",
    name: "Beast Master",
    description: "Slay 100 beasts named wolf, bear, boar, or cat — specifically, slay 100 wolves.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Hunter_RunningShot",
  },
  {
    id: "4012",
    name: "Bear Necessities",
    description: "Slay 50 bears.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Hunter_RunningShot",
  },
  {
    id: "4013",
    name: "Spider Smasher",
    description: "Slay 75 spiders.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Nature_Web",
  },
  {
    id: "4014",
    name: "Raptors Ate My Neighbor",
    description: "Slay 50 raptors.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Hunter_RunningShot",
  },
  {
    id: "4015",
    name: "Ogre Obliterator",
    description: "Slay 40 ogres.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_WarCry",
  },
  {
    id: "4016",
    name: "Elemental Equilibrium",
    description: "Slay 50 elementals.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Fire_Fire",
  },
  {
    id: "4017",
    name: "Dragonkin Dispatcher",
    description: "Slay 30 dragonkin or whelps.",
    category: "Combat",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_01",
  },
  {
    id: "4018",
    name: "Crit Happens",
    description: "Land 10 critical strikes.",
    category: "Combat",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_BackStab",
  },
  {
    id: "4019",
    name: "Critical Mass",
    description: "Land 100 critical strikes.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_BackStab",
  },
  {
    id: "4020",
    name: "RNG Blesses You",
    description: "Land 1,000 critical strikes.",
    category: "Combat",
    points: 20,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_SavageBlow",
  },
  {
    id: "4021",
    name: "That Was Close",
    description: "Survive combat after dropping to 10% health or lower.",
    category: "Combat",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfSacrifice",
  },
  {
    id: "4022",
    name: "Near-Death Experience",
    description: "Survive combat after dropping to 5% health or lower.",
    category: "Combat",
    points: 15,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_LifeDrain",
  },
  {
    id: "4023",
    name: "One HP Wonder",
    description: "Survive combat after dropping to 1% health or lower. Absolute cinema.",
    category: "Combat",
    points: 25,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfProtection",
  },
  {
    id: "4024",
    name: "Centurion",
    description: "Slay 100 creatures.",
    category: "Combat",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_OffensiveStance",
  },
  {
    id: "4025",
    name: "Hog Wild",
    description: "Slay 50 boars.",
    category: "Combat",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Food_60",
  },
  {
    id: "5001",
    name: "Errand Boy",
    description: "Complete your first quest.",
    category: "Quests",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Note_02",
  },
  {
    id: "5002",
    name: "Helpful Hand",
    description: "Complete 10 quests.",
    category: "Quests",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Note_01",
  },
  {
    id: "5003",
    name: "Questing Machine",
    description: "Complete 50 quests.",
    category: "Quests",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Note_03",
  },
  {
    id: "5004",
    name: "Loremaster in Training",
    description: "Complete 100 quests.",
    category: "Quests",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Book_09",
  },
  {
    id: "5005",
    name: "Walking Encyclopedia",
    description: "Complete 250 quests.",
    category: "Quests",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Book_11",
  },
  {
    id: "5006",
    name: "Questaholic",
    description: "Complete 500 quests.",
    category: "Quests",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Book_07",
  },
  {
    id: "5007",
    name: "No Job Too Small",
    description: "Complete 1,000 quests.",
    category: "Quests",
    points: 50,
    icon: "Interface\\\\Icons\\\\INV_Misc_Book_13",
  },
  {
    id: "6001",
    name: "Copper Pincher",
    description: "Loot a total of 1 gold.",
    category: "Wealth",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_05",
  },
  {
    id: "6002",
    name: "Pocket Change",
    description: "Loot a total of 10 gold.",
    category: "Wealth",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_03",
  },
  {
    id: "6003",
    name: "Comfortable Living",
    description: "Loot a total of 100 gold.",
    category: "Wealth",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_02",
  },
  {
    id: "6004",
    name: "Fat Stacks",
    description: "Loot a total of 500 gold.",
    category: "Wealth",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_01",
  },
  {
    id: "6005",
    name: "Gold Baron",
    description: "Loot a total of 1,000 gold.",
    category: "Wealth",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_15",
  },
  {
    id: "6006",
    name: "AH Whale",
    description: "Loot a total of 5,000 gold.",
    category: "Wealth",
    points: 50,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_17",
  },
  {
    id: "6007",
    name: "Shiny!",
    description: "Loot any item.",
    category: "Wealth",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Bag_05",
  },
  {
    id: "6008",
    name: "Pack Rat",
    description: "Loot 100 items.",
    category: "Wealth",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Bag_10",
  },
  {
    id: "6009",
    name: "Hoarder",
    description: "Loot 500 items.",
    category: "Wealth",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Bag_17",
  },
  {
    id: "6010",
    name: "Linen Lord",
    description: "Loot 20 items with \"Linen\" in the name.",
    category: "Wealth",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Fabric_Linen_01",
  },
  {
    id: "6011",
    name: "Woolly Bully",
    description: "Loot 20 items with \"Wool\" in the name.",
    category: "Wealth",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Fabric_Wool_01",
  },
  {
    id: "7001",
    name: "Apprentice Gathering",
    description: "Reach 50 Mining skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Mining",
  },
  {
    id: "7002",
    name: "Journeyman Miner",
    description: "Reach 150 Mining skill.",
    category: "Professions",
    points: 10,
    icon: "Interface\\\\Icons\\\\Trade_Mining",
  },
  {
    id: "7003",
    name: "Artisan Miner",
    description: "Reach 225 Mining skill.",
    category: "Professions",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Pick_02",
  },
  {
    id: "7004",
    name: "Master Miner",
    description: "Reach 300 Mining skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Pick_03",
  },
  {
    id: "7005",
    name: "Green Thumb",
    description: "Reach 75 Herbalism skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Herbalism",
  },
  {
    id: "7006",
    name: "Master Herbalist",
    description: "Reach 300 Herbalism skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Herb_17",
  },
  {
    id: "7007",
    name: "Thick Hide",
    description: "Reach 75 Skinning skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Pelt_Wolf_01",
  },
  {
    id: "7008",
    name: "Master Skinner",
    description: "Reach 300 Skinning skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Pelt_Bear_03",
  },
  {
    id: "7009",
    name: "Blacksmith's Apprentice",
    description: "Reach 75 Blacksmithing skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_BlackSmithing",
  },
  {
    id: "7010",
    name: "Master Blacksmith",
    description: "Reach 300 Blacksmithing skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Hammer_09",
  },
  {
    id: "7011",
    name: "Tailor's Apprentice",
    description: "Reach 75 Tailoring skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Tailoring",
  },
  {
    id: "7012",
    name: "Master Tailor",
    description: "Reach 300 Tailoring skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Fabric_Silk_02",
  },
  {
    id: "7013",
    name: "Leatherworker's Apprentice",
    description: "Reach 75 Leatherworking skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_ArmorKit_17",
  },
  {
    id: "7014",
    name: "Master Leatherworker",
    description: "Reach 300 Leatherworking skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_ArmorKit_17",
  },
  {
    id: "7015",
    name: "Alchemist's Apprentice",
    description: "Reach 75 Alchemy skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Alchemy",
  },
  {
    id: "7016",
    name: "Master Alchemist",
    description: "Reach 300 Alchemy skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Potion_27",
  },
  {
    id: "7017",
    name: "Engineer's Apprentice",
    description: "Reach 75 Engineering skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Engineering",
  },
  {
    id: "7018",
    name: "Master Engineer",
    description: "Reach 300 Engineering skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Gizmo_01",
  },
  {
    id: "7019",
    name: "Enchanter's Apprentice",
    description: "Reach 75 Enchanting skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Engraving",
  },
  {
    id: "7020",
    name: "Master Enchanter",
    description: "Reach 300 Enchanting skill.",
    category: "Professions",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Enchant_DustArcane",
  },
  {
    id: "7021",
    name: "First Aid Novice",
    description: "Reach 75 First Aid skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SealOfSacrifice",
  },
  {
    id: "7022",
    name: "Field Medic",
    description: "Reach 300 First Aid skill.",
    category: "Professions",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Bandage_12",
  },
  {
    id: "7023",
    name: "Cooking Novice",
    description: "Reach 75 Cooking skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Food_15",
  },
  {
    id: "7024",
    name: "Chef de Cuisine",
    description: "Reach 300 Cooking skill.",
    category: "Professions",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Food_64",
  },
  {
    id: "7025",
    name: "Angler's Apprentice",
    description: "Reach 75 Fishing skill.",
    category: "Professions",
    points: 5,
    icon: "Interface\\\\Icons\\\\Trade_Fishing",
  },
  {
    id: "7026",
    name: "Old Salt",
    description: "Reach 300 Fishing skill.",
    category: "Professions",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Fish_02",
  },
  {
    id: "8001",
    name: "Dungeon Delver",
    description: "Enter any dungeon or raid.",
    category: "Dungeons",
    points: 5,
    icon: "Interface\\\\Icons\\\\INV_Misc_Key_11",
  },
  {
    id: "8002",
    name: "Instance Hopper",
    description: "Enter 5 different dungeons or raids.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Key_11",
  },
  {
    id: "8003",
    name: "Keyring Collector",
    description: "Enter 10 different dungeons or raids.",
    category: "Dungeons",
    points: 20,
    icon: "Interface\\\\Icons\\\\INV_Misc_Key_08",
  },
  {
    id: "8004",
    name: "Dead Mines, Live Heroes",
    description: "Enter The Deadmines.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Rogue_Disguise",
  },
  {
    id: "8005",
    name: "Wailing in the Depths",
    description: "Enter Wailing Caverns.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Nature_Acid_01",
  },
  {
    id: "8006",
    name: "Shadowfang Sojourn",
    description: "Enter Shadowfang Keep.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_ShadowBolt",
  },
  {
    id: "8007",
    name: "Stockade Stint",
    description: "Enter The Stockade.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_SummonVoidWalker",
  },
  {
    id: "8008",
    name: "Razorfen Run",
    description: "Enter Razorfen Kraul or Razorfen Downs.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Frost_FrostBolt02",
  },
  {
    id: "8009",
    name: "Gnomeregan Infiltration",
    description: "Enter Gnomeregan.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Gizmo_01",
  },
  {
    id: "8010",
    name: "Scarlet Letter",
    description: "Enter a Scarlet Monastery wing.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Holy_PrayerOfHealing",
  },
  {
    id: "8011",
    name: "Uldaman Unearthed",
    description: "Enter Uldaman.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Pick_03",
  },
  {
    id: "8012",
    name: "Zul'Farrak Vacation",
    description: "Enter Zul'Farrak.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Troll_01",
  },
  {
    id: "8013",
    name: "Maraudon Mayhem",
    description: "Enter Maraudon.",
    category: "Dungeons",
    points: 10,
    icon: "Interface\\\\Icons\\\\Spell_Nature_Earthquake",
  },
  {
    id: "8014",
    name: "Temple of Atal'Hakkar",
    description: "Enter the Sunken Temple.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_Green",
  },
  {
    id: "8015",
    name: "Blackrock Depths",
    description: "Enter Blackrock Depths.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_Black",
  },
  {
    id: "8016",
    name: "Lower Blackrock Spire",
    description: "Enter Lower Blackrock Spire.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_01",
  },
  {
    id: "8017",
    name: "Stratholme Bound",
    description: "Enter Stratholme.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_DeathCoil",
  },
  {
    id: "8018",
    name: "Scholomance Bound",
    description: "Enter Scholomance.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\Spell_Frost_IceStorm",
  },
  {
    id: "8019",
    name: "Onyxia's Lair",
    description: "Enter Onyxia's Lair.",
    category: "Dungeons",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_01",
  },
  {
    id: "8020",
    name: "Molten Core Bound",
    description: "Enter Molten Core.",
    category: "Dungeons",
    points: 25,
    icon: "Interface\\\\Icons\\\\Spell_Fire_Fire",
  },
  {
    id: "8021",
    name: "Blackwing Lair Bound",
    description: "Enter Blackwing Lair.",
    category: "Dungeons",
    points: 25,
    icon: "Interface\\\\Icons\\\\INV_Misc_Head_Dragon_Black",
  },
  {
    id: "8022",
    name: "Ahn'Qiraj Bound",
    description: "Enter the Temple of Ahn'Qiraj or Ruins of Ahn'Qiraj.",
    category: "Dungeons",
    points: 25,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_ShadowWordPain",
  },
  {
    id: "8023",
    name: "Naxxramas Bound",
    description: "Enter Naxxramas.",
    category: "Dungeons",
    points: 25,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_RaiseDead",
  },
  {
    id: "8024",
    name: "VanCleef Vanquished",
    description: "Slay Edwin VanCleef.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\Ability_Rogue_Disguise",
  },
  {
    id: "8025",
    name: "Mutanus Muted",
    description: "Slay Mutanus the Devourer.",
    category: "Dungeons",
    points: 15,
    icon: "Interface\\\\Icons\\\\Spell_Nature_Acid_01",
  },
  {
    id: "9001",
    name: "Did Somebody Say...?",
    description: "Reach level 60. The world is yours.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\Spell_Holy_SummonChampion",
  },
  {
    id: "9002",
    name: "Undying Legend",
    description: "Reach level 60 without ever dying. A true Hardcore legend.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\Spell_Holy_HolyBolt",
  },
  {
    id: "9003",
    name: "Millionaire",
    description: "Loot a total of 10,000 gold.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\INV_Misc_Coin_17",
  },
  {
    id: "9004",
    name: "Genocide Adjacent",
    description: "Slay 10,000 creatures.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\Spell_Shadow_DeathPact",
  },
  {
    id: "9005",
    name: "The Real Loremaster",
    description: "Complete 2,000 quests.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\INV_Misc_Book_13",
  },
  {
    id: "9006",
    name: "World Traveler",
    description: "Visit 50 different zones.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\INV_Misc_Map_01",
  },
  {
    id: "9007",
    name: "Key to the Kingdom",
    description: "Enter 20 different dungeons or raids.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\INV_Misc_Key_07",
  },
  {
    id: "9008",
    name: "Grandmaster of Everything",
    description: "Earn 150 achievements.",
    category: "Feats of Strength",
    points: 0,
    icon: "Interface\\\\Icons\\\\INV_Jewelry_Talisman_08",
  },
  {
    id: "10001",
    name: "Duelist",
    description: "Win a duel.",
    category: "Player vs Player",
    points: 5,
    icon: "Interface\\\\Icons\\\\Ability_DualWield",
  },
  {
    id: "10002",
    name: "Sparring Partner",
    description: "Win 5 duels.",
    category: "Player vs Player",
    points: 10,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_Revenge",
  },
  {
    id: "10003",
    name: "Arena Warmup",
    description: "Win 25 duels.",
    category: "Player vs Player",
    points: 15,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_Revenge",
  },
  {
    id: "10004",
    name: "Duel Master",
    description: "Win 100 duels.",
    category: "Player vs Player",
    points: 25,
    icon: "Interface\\\\Icons\\\\Ability_Warrior_DecisiveStrike",
  },
];

/** Used for leaderboard "dungeon clears" sort (Dungeons category). */
export const BOSS_ACHIEVEMENT_IDS = [
  "8001",
  "8002",
  "8003",
  "8004",
  "8005",
  "8006",
  "8007",
  "8008",
  "8009",
  "8010",
  "8011",
  "8012",
  "8013",
  "8014",
  "8015",
  "8016",
  "8017",
  "8018",
  "8019",
  "8020",
  "8021",
  "8022",
  "8023",
  "8024",
  "8025",
] as const;

const byId = new Map(ACHIEVEMENT_CATALOG.map((a) => [a.id, a]));

export function getAchievementById(id: string): AchievementDefinition | undefined {
  return byId.get(id);
}
