/** Criteria rules extracted from ClassicGlory/Data.lua. Do not edit by hand. */

export type AchievementCriterionRule = {
  type: string;
  value: number;
  match?: string;
  threshold?: number;
  standing?: string;
};

export type AchievementRule = {
  hcOnly?: boolean;
  criteria: AchievementCriterionRule[];
};

export const ACHIEVEMENT_RULES: Record<string, AchievementRule> = {
  "1001": {"criteria":[{"type":"LEVEL","value":2}]},
  "1002": {"criteria":[{"type":"LEVEL","value":5}]},
  "1003": {"criteria":[{"type":"LEVEL","value":10}]},
  "1004": {"criteria":[{"type":"LEVEL","value":20}]},
  "1005": {"criteria":[{"type":"LEVEL","value":30}]},
  "1006": {"criteria":[{"type":"LEVEL","value":40}]},
  "1007": {"criteria":[{"type":"LEVEL","value":50}]},
  "1008": {"criteria":[{"type":"LEVEL","value":55}]},
  "1009": {"criteria":[{"type":"LEVEL","value":58}]},
  "1010": {"criteria":[{"type":"LOGIN","value":1}]},
  "1011": {"criteria":[{"type":"FACTION","value":1,"match":"Alliance"}]},
  "1012": {"criteria":[{"type":"FACTION","value":1,"match":"Horde"}]},
  "1013": {"criteria":[{"type":"RACE","value":1,"match":"Human"}]},
  "1014": {"criteria":[{"type":"RACE","value":1,"match":"Dwarf"}]},
  "1015": {"criteria":[{"type":"RACE","value":1,"match":"NightElf"}]},
  "1016": {"criteria":[{"type":"RACE","value":1,"match":"Gnome"}]},
  "1017": {"criteria":[{"type":"RACE","value":1,"match":"Orc"}]},
  "1018": {"criteria":[{"type":"RACE","value":1,"match":"Scourge"}]},
  "1019": {"criteria":[{"type":"RACE","value":1,"match":"Tauren"}]},
  "1020": {"criteria":[{"type":"RACE","value":1,"match":"Troll"}]},
  "1021": {"criteria":[{"type":"CLASS","value":1,"match":"WARRIOR"}]},
  "1022": {"criteria":[{"type":"CLASS","value":1,"match":"PALADIN"}]},
  "1023": {"criteria":[{"type":"CLASS","value":1,"match":"HUNTER"}]},
  "1024": {"criteria":[{"type":"CLASS","value":1,"match":"ROGUE"}]},
  "1025": {"criteria":[{"type":"CLASS","value":1,"match":"PRIEST"}]},
  "1026": {"criteria":[{"type":"CLASS","value":1,"match":"SHAMAN"}]},
  "1027": {"criteria":[{"type":"CLASS","value":1,"match":"MAGE"}]},
  "1028": {"criteria":[{"type":"CLASS","value":1,"match":"WARLOCK"}]},
  "1029": {"criteria":[{"type":"CLASS","value":1,"match":"DRUID"}]},
  "1030": {"criteria":[{"type":"EMOTES","value":25}]},
  "1031": {"criteria":[{"type":"EMOTES","value":1,"match":"dance"}]},
  "1032": {"criteria":[{"type":"META","value":25}]},
  "1033": {"criteria":[{"type":"META","value":50}]},
  "1034": {"criteria":[{"type":"META","value":100}]},
  "1035": {"criteria":[{"type":"REP","value":1,"match":"Stormwind","standing":"Friendly"}]},
  "1036": {"criteria":[{"type":"REP","value":1,"match":"Stormwind","standing":"Honored"}]},
  "1037": {"criteria":[{"type":"REP","value":1,"match":"Orgrimmar","standing":"Friendly"}]},
  "1038": {"criteria":[{"type":"REP","value":1,"match":"Orgrimmar","standing":"Honored"}]},
  "1039": {"criteria":[{"type":"REP","value":1,"match":"Argent Dawn","standing":"Friendly"}]},
  "1040": {"criteria":[{"type":"REP","value":1,"match":"Timbermaw","standing":"Friendly"}]},
  "2001": {"criteria":[{"type":"LOGIN","value":1}],"hcOnly":true},
  "2002": {"criteria":[{"type":"DEATHLESS","value":10}],"hcOnly":true},
  "2003": {"criteria":[{"type":"DEATHLESS","value":20}],"hcOnly":true},
  "2004": {"criteria":[{"type":"DEATHLESS","value":30}],"hcOnly":true},
  "2005": {"criteria":[{"type":"DEATHLESS","value":40}],"hcOnly":true},
  "2006": {"criteria":[{"type":"DEATHLESS","value":50}],"hcOnly":true},
  "2007": {"criteria":[{"type":"DEATHLESS","value":60}],"hcOnly":true},
  "2008": {"criteria":[{"type":"HEALTH","value":1,"threshold":5}],"hcOnly":true},
  "2009": {"criteria":[{"type":"HEALTH","value":1,"threshold":1}],"hcOnly":true},
  "2010": {"criteria":[{"type":"QUESTS","value":50},{"type":"DEATHLESS","value":1}],"hcOnly":true},
  "2011": {"criteria":[{"type":"SKILL","value":150,"match":"Mining"}],"hcOnly":true},
  "2012": {"criteria":[{"type":"INSTANCE","value":1}],"hcOnly":true},
  "2013": {"criteria":[{"type":"DEATHS","value":1}]},
  "2014": {"criteria":[{"type":"DEATHS","value":10}]},
  "3001": {"criteria":[{"type":"ZONES","value":5}]},
  "3002": {"criteria":[{"type":"ZONES","value":10}]},
  "3003": {"criteria":[{"type":"ZONES","value":20}]},
  "3004": {"criteria":[{"type":"ZONES","value":35}]},
  "3005": {"criteria":[{"type":"ZONE","value":1,"match":"Elwynn"}]},
  "3006": {"criteria":[{"type":"ZONE","value":1,"match":"Westfall"}]},
  "3007": {"criteria":[{"type":"ZONE","value":1,"match":"Redridge"}]},
  "3008": {"criteria":[{"type":"ZONE","value":1,"match":"Duskwood"}]},
  "3009": {"criteria":[{"type":"ZONE","value":1,"match":"Stranglethorn"}]},
  "3010": {"criteria":[{"type":"ZONE","value":1,"match":"Durotar"}]},
  "3011": {"criteria":[{"type":"ZONE","value":1,"match":"Barrens"}]},
  "3012": {"criteria":[{"type":"ZONE","value":1,"match":"Mulgore"}]},
  "3013": {"criteria":[{"type":"ZONE","value":1,"match":"Ashenvale"}]},
  "3014": {"criteria":[{"type":"ZONE","value":1,"match":"Wetlands"}]},
  "3015": {"criteria":[{"type":"ZONE","value":1,"match":"Hillsbrad"}]},
  "3016": {"criteria":[{"type":"ZONE","value":1,"match":"Tanaris"}]},
  "3017": {"criteria":[{"type":"ZONE","value":1,"match":"Un'Goro"}]},
  "3018": {"criteria":[{"type":"ZONE","value":1,"match":"Winterspring"}]},
  "3019": {"criteria":[{"type":"ZONE","value":1,"match":"Blasted Lands"}]},
  "3020": {"criteria":[{"type":"ZONE","value":1,"match":"Stormwind"}]},
  "3021": {"criteria":[{"type":"ZONE","value":1,"match":"Orgrimmar"}]},
  "3022": {"criteria":[{"type":"ZONE","value":1,"match":"Ironforge"}]},
  "3023": {"criteria":[{"type":"ZONE","value":1,"match":"Undercity"}]},
  "3024": {"criteria":[{"type":"ZONE","value":1,"match":"Thunder Bluff"}]},
  "3025": {"criteria":[{"type":"ZONE","value":1,"match":"Darnassus"}]},
  "3026": {"criteria":[{"type":"ZONE","value":1,"match":"Elwynn"},{"type":"ZONE","value":1,"match":"Westfall"},{"type":"ZONE","value":1,"match":"Redridge"}]},
  "3027": {"criteria":[{"type":"ZONE","value":1,"match":"Durotar"},{"type":"ZONE","value":1,"match":"Barrens"},{"type":"ZONE","value":1,"match":"Mulgore"}]},
  "3028": {"criteria":[{"type":"ZONE","value":1,"match":"Burning Steppes"}]},
  "3029": {"criteria":[{"type":"ZONE","value":1,"match":"Hinterlands"}]},
  "3030": {"criteria":[{"type":"ZONE","value":1,"match":"Silithus"}]},
  "4001": {"criteria":[{"type":"KILLS","value":1}]},
  "4002": {"criteria":[{"type":"KILLS","value":50}]},
  "4003": {"criteria":[{"type":"KILLS","value":250}]},
  "4004": {"criteria":[{"type":"KILLS","value":1000}]},
  "4005": {"criteria":[{"type":"KILLS","value":5000}]},
  "4006": {"criteria":[{"type":"KILLS","value":100,"match":"murloc"}]},
  "4007": {"criteria":[{"type":"KILLS","value":50,"match":"gnoll"}]},
  "4008": {"criteria":[{"type":"KILLS","value":50,"match":"kobold"}]},
  "4009": {"criteria":[{"type":"KILLS","value":50,"match":"defias"}]},
  "4010": {"criteria":[{"type":"KILLS","value":100,"match":"skeleton"}]},
  "4011": {"criteria":[{"type":"KILLS","value":100,"match":"wolf"}]},
  "4012": {"criteria":[{"type":"KILLS","value":50,"match":"bear"}]},
  "4013": {"criteria":[{"type":"KILLS","value":75,"match":"spider"}]},
  "4014": {"criteria":[{"type":"KILLS","value":50,"match":"raptor"}]},
  "4015": {"criteria":[{"type":"KILLS","value":40,"match":"ogre"}]},
  "4016": {"criteria":[{"type":"KILLS","value":50,"match":"elemental"}]},
  "4017": {"criteria":[{"type":"KILLS","value":30,"match":"whelp"}]},
  "4018": {"criteria":[{"type":"CRITS","value":10}]},
  "4019": {"criteria":[{"type":"CRITS","value":100}]},
  "4020": {"criteria":[{"type":"CRITS","value":1000}]},
  "4021": {"criteria":[{"type":"HEALTH","value":1,"threshold":10}]},
  "4022": {"criteria":[{"type":"HEALTH","value":1,"threshold":5}]},
  "4023": {"criteria":[{"type":"HEALTH","value":1,"threshold":1}]},
  "4024": {"criteria":[{"type":"KILLS","value":100}]},
  "4025": {"criteria":[{"type":"KILLS","value":50,"match":"boar"}]},
  "5001": {"criteria":[{"type":"QUESTS","value":1}]},
  "5002": {"criteria":[{"type":"QUESTS","value":10}]},
  "5003": {"criteria":[{"type":"QUESTS","value":50}]},
  "5004": {"criteria":[{"type":"QUESTS","value":100}]},
  "5005": {"criteria":[{"type":"QUESTS","value":250}]},
  "5006": {"criteria":[{"type":"QUESTS","value":500}]},
  "5007": {"criteria":[{"type":"QUESTS","value":1000}]},
  "6001": {"criteria":[{"type":"MONEY","value":1}]},
  "6002": {"criteria":[{"type":"MONEY","value":10}]},
  "6003": {"criteria":[{"type":"MONEY","value":100}]},
  "6004": {"criteria":[{"type":"MONEY","value":500}]},
  "6005": {"criteria":[{"type":"MONEY","value":1000}]},
  "6006": {"criteria":[{"type":"MONEY","value":5000}]},
  "6007": {"criteria":[{"type":"LOOT","value":1}]},
  "6008": {"criteria":[{"type":"LOOT","value":100}]},
  "6009": {"criteria":[{"type":"LOOT","value":500}]},
  "6010": {"criteria":[{"type":"LOOT","value":20,"match":"Linen"}]},
  "6011": {"criteria":[{"type":"LOOT","value":20,"match":"Wool"}]},
  "7001": {"criteria":[{"type":"SKILL","value":50,"match":"Mining"}]},
  "7002": {"criteria":[{"type":"SKILL","value":150,"match":"Mining"}]},
  "7003": {"criteria":[{"type":"SKILL","value":225,"match":"Mining"}]},
  "7004": {"criteria":[{"type":"SKILL","value":300,"match":"Mining"}]},
  "7005": {"criteria":[{"type":"SKILL","value":75,"match":"Herbalism"}]},
  "7006": {"criteria":[{"type":"SKILL","value":300,"match":"Herbalism"}]},
  "7007": {"criteria":[{"type":"SKILL","value":75,"match":"Skinning"}]},
  "7008": {"criteria":[{"type":"SKILL","value":300,"match":"Skinning"}]},
  "7009": {"criteria":[{"type":"SKILL","value":75,"match":"Blacksmithing"}]},
  "7010": {"criteria":[{"type":"SKILL","value":300,"match":"Blacksmithing"}]},
  "7011": {"criteria":[{"type":"SKILL","value":75,"match":"Tailoring"}]},
  "7012": {"criteria":[{"type":"SKILL","value":300,"match":"Tailoring"}]},
  "7013": {"criteria":[{"type":"SKILL","value":75,"match":"Leatherworking"}]},
  "7014": {"criteria":[{"type":"SKILL","value":300,"match":"Leatherworking"}]},
  "7015": {"criteria":[{"type":"SKILL","value":75,"match":"Alchemy"}]},
  "7016": {"criteria":[{"type":"SKILL","value":300,"match":"Alchemy"}]},
  "7017": {"criteria":[{"type":"SKILL","value":75,"match":"Engineering"}]},
  "7018": {"criteria":[{"type":"SKILL","value":300,"match":"Engineering"}]},
  "7019": {"criteria":[{"type":"SKILL","value":75,"match":"Enchanting"}]},
  "7020": {"criteria":[{"type":"SKILL","value":300,"match":"Enchanting"}]},
  "7021": {"criteria":[{"type":"SKILL","value":75,"match":"First Aid"}]},
  "7022": {"criteria":[{"type":"SKILL","value":300,"match":"First Aid"}]},
  "7023": {"criteria":[{"type":"SKILL","value":75,"match":"Cooking"}]},
  "7024": {"criteria":[{"type":"SKILL","value":300,"match":"Cooking"}]},
  "7025": {"criteria":[{"type":"SKILL","value":75,"match":"Fishing"}]},
  "7026": {"criteria":[{"type":"SKILL","value":300,"match":"Fishing"}]},
  "8001": {"criteria":[{"type":"INSTANCE","value":1}]},
  "8002": {"criteria":[{"type":"INSTANCE","value":5}]},
  "8003": {"criteria":[{"type":"INSTANCE","value":10}]},
  "8004": {"criteria":[{"type":"INSTANCE","value":1,"match":"Deadmines"}]},
  "8005": {"criteria":[{"type":"INSTANCE","value":1,"match":"Wailing Caverns"}]},
  "8006": {"criteria":[{"type":"INSTANCE","value":1,"match":"Shadowfang"}]},
  "8007": {"criteria":[{"type":"INSTANCE","value":1,"match":"Stockade"}]},
  "8008": {"criteria":[{"type":"INSTANCE","value":1,"match":"Razorfen"}]},
  "8009": {"criteria":[{"type":"INSTANCE","value":1,"match":"Gnomeregan"}]},
  "8010": {"criteria":[{"type":"INSTANCE","value":1,"match":"Scarlet"}]},
  "8011": {"criteria":[{"type":"INSTANCE","value":1,"match":"Uldaman"}]},
  "8012": {"criteria":[{"type":"INSTANCE","value":1,"match":"Zul'Farrak"}]},
  "8013": {"criteria":[{"type":"INSTANCE","value":1,"match":"Maraudon"}]},
  "8014": {"criteria":[{"type":"INSTANCE","value":1,"match":"Temple of Atal"}]},
  "8015": {"criteria":[{"type":"INSTANCE","value":1,"match":"Blackrock Depths"}]},
  "8016": {"criteria":[{"type":"INSTANCE","value":1,"match":"Blackrock Spire"}]},
  "8017": {"criteria":[{"type":"INSTANCE","value":1,"match":"Stratholme"}]},
  "8018": {"criteria":[{"type":"INSTANCE","value":1,"match":"Scholomance"}]},
  "8019": {"criteria":[{"type":"INSTANCE","value":1,"match":"Onyxia"}]},
  "8020": {"criteria":[{"type":"INSTANCE","value":1,"match":"Molten Core"}]},
  "8021": {"criteria":[{"type":"INSTANCE","value":1,"match":"Blackwing"}]},
  "8022": {"criteria":[{"type":"INSTANCE","value":1,"match":"Ahn'Qiraj"}]},
  "8023": {"criteria":[{"type":"INSTANCE","value":1,"match":"Naxxramas"}]},
  "8024": {"criteria":[{"type":"KILLS","value":1,"match":"Edwin VanCleef"}]},
  "8025": {"criteria":[{"type":"KILLS","value":1,"match":"Mutanus"}]},
  "9001": {"criteria":[{"type":"LEVEL","value":60}]},
  "9002": {"criteria":[{"type":"DEATHLESS","value":60}],"hcOnly":true},
  "9003": {"criteria":[{"type":"MONEY","value":10000}]},
  "9004": {"criteria":[{"type":"KILLS","value":10000}]},
  "9005": {"criteria":[{"type":"QUESTS","value":2000}]},
  "9006": {"criteria":[{"type":"ZONES","value":50}]},
  "9007": {"criteria":[{"type":"INSTANCE","value":20}]},
  "9008": {"criteria":[{"type":"META","value":150}]},
  "10001": {"criteria":[{"type":"DUELS","value":1}]},
  "10002": {"criteria":[{"type":"DUELS","value":5}]},
  "10003": {"criteria":[{"type":"DUELS","value":25}]},
  "10004": {"criteria":[{"type":"DUELS","value":100}]},
};
