-- Adapt existing Achieve-mint project to Laucobs Achievements catalog and stats.

-- Old unlocks reference Achieve-mint IDs that will be replaced.
truncate table public.character_achievements;

update public.characters
set total_points = 0,
    achievement_count = 0;

alter table public.achievements
  drop constraint if exists achievements_category_check;

delete from public.achievements;

alter table public.achievements
  add constraint achievements_category_check
  check (category in (
    'General',
    'Quests',
    'Combat',
    'Exploration',
    'Wealth',
    'Professions',
    'Dungeons',
    'Player vs Player',
    'Hardcore',
    'Feats of Strength'
  ));

alter table public.character_stats
  add column if not exists deaths integer not null default 0;

alter table public.character_stats
  drop column if exists quests_turned_in,
  drop column if exists lowest_hp_pct,
  drop column if exists survived_low_hp,
  drop column if exists naked_until_10;

-- Seed Laucobs Achievements catalog (190 achievements)
insert into public.achievements (id, name, description, category, points, icon)
values
  ('1001', 'Fresh Meat', 'Create a character and take your first steps into Azeroth. Reach level 2.', 'General', 5, 'Interface\\Icons\\Spell_Nature_Regeneration'),
  ('1002', 'Out of the Nest', 'Reach level 5.', 'General', 5, 'Interface\\Icons\\Ability_Warrior_BattleShout'),
  ('1003', 'Double Digits', 'Reach level 10.', 'General', 10, 'Interface\\Icons\\Spell_Nature_Strength'),
  ('1004', 'Getting Dangerous', 'Reach level 20.', 'General', 10, 'Interface\\Icons\\Ability_DualWield'),
  ('1005', 'Halfway Hero', 'Reach level 30.', 'General', 10, 'Interface\\Icons\\Spell_Holy_SealOfMight'),
  ('1006', 'Seasoned Adventurer', 'Reach level 40.', 'General', 15, 'Interface\\Icons\\Ability_TownWatch'),
  ('1007', 'Elite Contender', 'Reach level 50.', 'General', 20, 'Interface\\Icons\\Spell_Holy_SealOfWisdom'),
  ('1008', 'The Climb', 'Reach level 55.', 'General', 20, 'Interface\\Icons\\Spell_Nature_EarthBind'),
  ('1009', 'Ready for Anything', 'Reach level 58 — the gates of endgame beckon.', 'General', 25, 'Interface\\Icons\\INV_Misc_Head_Dragon_01'),
  ('1010', 'Well-Rested', 'Log in to Azeroth. Welcome back, hero.', 'General', 5, 'Interface\\Icons\\Spell_Holy_SealOfWisdom'),
  ('1011', 'For the Alliance!', 'Create an Alliance character.', 'General', 5, 'Interface\\Icons\\INV_BannerPVP_02'),
  ('1012', 'For the Horde!', 'Create a Horde character.', 'General', 5, 'Interface\\Icons\\INV_BannerPVP_01'),
  ('1013', 'Lionheart', 'Create a Human.', 'General', 5, 'Interface\\Icons\\Spell_Holy_HolyBolt'),
  ('1014', 'By Hammer and Anvil', 'Create a Dwarf.', 'General', 5, 'Interface\\Icons\\INV_Drink_04'),
  ('1015', 'Child of the Stars', 'Create a Night Elf.', 'General', 5, 'Interface\\Icons\\Ability_Ambush'),
  ('1016', 'Gnomish Ingenuity', 'Create a Gnome.', 'General', 5, 'Interface\\Icons\\INV_Gizmo_01'),
  ('1017', 'Lok''tar Ogar', 'Create an Orc.', 'General', 5, 'Interface\\Icons\\Ability_Warrior_WarCry'),
  ('1018', 'Death Becomes You', 'Create an Undead.', 'General', 5, 'Interface\\Icons\\Spell_Shadow_RaiseDead'),
  ('1019', 'Walks with the Earthmother', 'Create a Tauren.', 'General', 5, 'Interface\\Icons\\Spell_Nature_HealingTouch'),
  ('1020', 'Voodoo Shuffle', 'Create a Troll.', 'General', 5, 'Interface\\Icons\\Spell_Shadow_ShadowWordPain'),
  ('1021', 'Arms Wide Open', 'Play as a Warrior.', 'General', 5, 'Interface\\Icons\\INV_Sword_27'),
  ('1022', 'Light''s Favored', 'Play as a Paladin.', 'General', 5, 'Interface\\Icons\\Spell_Holy_SealOfMight'),
  ('1023', 'Hunter''s Path', 'Play as a Hunter.', 'General', 5, 'Interface\\Icons\\Ability_Hunter_RunningShot'),
  ('1024', 'Shadow Dance', 'Play as a Rogue.', 'General', 5, 'Interface\\Icons\\Ability_Stealth'),
  ('1025', 'Faithful Servant', 'Play as a Priest.', 'General', 5, 'Interface\\Icons\\Spell_Holy_PowerWordShield'),
  ('1026', 'Elemental Affinity', 'Play as a Shaman.', 'General', 5, 'Interface\\Icons\\Spell_Nature_BloodLust'),
  ('1027', 'Arcane Ambition', 'Play as a Mage.', 'General', 5, 'Interface\\Icons\\Spell_Frost_IceStorm'),
  ('1028', 'Pact Maker', 'Play as a Warlock.', 'General', 5, 'Interface\\Icons\\Spell_Shadow_ShadowBolt'),
  ('1029', 'Wild Shape of Mind', 'Play as a Druid.', 'General', 5, 'Interface\\Icons\\Spell_Nature_HealingTouch'),
  ('1030', 'Social Butterfly', '/wave, /dance, or otherwise emote 25 times.', 'General', 5, 'Interface\\Icons\\Spell_Shadow_Charm'),
  ('1031', 'Party Starter', 'Dance it out — use a /dance emote.', 'General', 5, 'Interface\\Icons\\Spell_Holy_HolyBolt'),
  ('1032', 'Achievement Addict', 'Earn 25 achievements.', 'General', 10, 'Interface\\Icons\\INV_Jewelry_Talisman_08'),
  ('1033', 'Overachiever', 'Earn 50 achievements.', 'General', 20, 'Interface\\Icons\\INV_Jewelry_Talisman_08'),
  ('1034', 'Completionist Tendencies', 'Earn 100 achievements.', 'General', 50, 'Interface\\Icons\\INV_Jewelry_Talisman_08'),
  ('1035', 'Friendly Face', 'Become Friendly with Stormwind.', 'General', 5, 'Interface\\Icons\\INV_Misc_GroupLooking'),
  ('1036', 'Honored Guest', 'Become Honored with Stormwind.', 'General', 10, 'Interface\\Icons\\INV_Misc_GroupLooking'),
  ('1037', 'Lok''tar Reputation', 'Become Friendly with Orgrimmar.', 'General', 5, 'Interface\\Icons\\INV_Misc_GroupLooking'),
  ('1038', 'Orgrimmar Honored', 'Become Honored with Orgrimmar.', 'General', 10, 'Interface\\Icons\\INV_Misc_GroupLooking'),
  ('1039', 'Argent Dawn Ally', 'Become Friendly with the Argent Dawn.', 'General', 10, 'Interface\\Icons\\INV_Jewelry_Talisman_07'),
  ('1040', 'Timbermaw Friend', 'Become Friendly with Timbermaw Hold.', 'General', 10, 'Interface\\Icons\\INV_Misc_MonsterClaw_04'),
  ('2001', 'Permadeath Protocol', 'Log in on a Hardcore character.', 'Hardcore', 5, 'Interface\\Icons\\Ability_Warrior_DefensiveStance'),
  ('2002', 'Still Breathing', 'Reach level 10 without dying on Hardcore.', 'Hardcore', 10, 'Interface\\Icons\\Spell_Holy_SealOfProtection'),
  ('2003', 'Greenhorn Survivor', 'Reach level 20 without dying on Hardcore.', 'Hardcore', 15, 'Interface\\Icons\\Ability_Warrior_DefensiveStance'),
  ('2004', 'Hardened', 'Reach level 30 without dying on Hardcore.', 'Hardcore', 20, 'Interface\\Icons\\INV_Shield_06'),
  ('2005', 'Iron Will', 'Reach level 40 without dying on Hardcore.', 'Hardcore', 25, 'Interface\\Icons\\INV_Shield_05'),
  ('2006', 'Unbreakable', 'Reach level 50 without dying on Hardcore.', 'Hardcore', 35, 'Interface\\Icons\\INV_Shield_04'),
  ('2007', 'Immortal Contender', 'Reach level 60 without dying on Hardcore.', 'Hardcore', 50, 'Interface\\Icons\\Spell_Holy_HolyBolt'),
  ('2008', 'Sweaty Palms', 'On Hardcore, survive combat after dropping to 5% health.', 'Hardcore', 15, 'Interface\\Icons\\Spell_Shadow_LifeDrain'),
  ('2009', 'Heart Attack Simulator', 'On Hardcore, survive combat after dropping to 1% health.', 'Hardcore', 25, 'Interface\\Icons\\Spell_Holy_SealOfSacrifice'),
  ('2010', 'Cautious Adventurer', 'On Hardcore, complete 50 quests without dying.', 'Hardcore', 15, 'Interface\\Icons\\INV_Misc_Note_02'),
  ('2011', 'Self-Sufficient', 'On Hardcore, reach 150 skill in any gathering profession.', 'Hardcore', 10, 'Interface\\Icons\\Trade_Mining'),
  ('2012', 'Dungeon? On Hardcore?', 'Enter a dungeon on a Hardcore character. Bold strategy.', 'Hardcore', 20, 'Interface\\Icons\\INV_Misc_Key_11'),
  ('2013', 'Death''s Door', 'Die once. (Not recommended on Hardcore.)', 'Hardcore', 0, 'Interface\\Icons\\Spell_Shadow_DeathCoil'),
  ('2014', 'Frequent Flyer', 'Die 10 times. The spirit healer knows your name.', 'Hardcore', 0, 'Interface\\Icons\\Spell_Shadow_Twilight'),
  ('3001', 'Tourist', 'Visit 5 different zones.', 'Exploration', 5, 'Interface\\Icons\\Ability_TownWatch'),
  ('3002', 'Wanderer', 'Visit 10 different zones.', 'Exploration', 10, 'Interface\\Icons\\Ability_Tracking'),
  ('3003', 'Globe-Trotter', 'Visit 20 different zones.', 'Exploration', 15, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3004', 'Cartographer', 'Visit 35 different zones.', 'Exploration', 25, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3005', 'Elwynn Bound', 'Visit Elwynn Forest.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3006', 'Westfall Bound', 'Visit Westfall.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3007', 'Redridge Bound', 'Visit Redridge Mountains.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3008', 'Duskwood Bound', 'Visit Duskwood.', 'Exploration', 5, 'Interface\\Icons\\Spell_Shadow_Twilight'),
  ('3009', 'Into the Jungle', 'Visit Stranglethorn Vale.', 'Exploration', 10, 'Interface\\Icons\\Ability_Hunter_RunningShot'),
  ('3010', 'Durotar Bound', 'Visit Durotar.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3011', 'Barrens Chat', 'Visit The Barrens. May the chat forgive you.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3012', 'Mulgore Bound', 'Visit Mulgore.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3013', 'Ashenvale Bound', 'Visit Ashenvale.', 'Exploration', 5, 'Interface\\Icons\\Spell_Nature_ProtectionForm'),
  ('3014', 'Wetlands Bound', 'Visit the Wetlands.', 'Exploration', 5, 'Interface\\Icons\\Spell_Frost_SummonWaterElemental'),
  ('3015', 'Hillsbrad Bound', 'Visit Hillsbrad Foothills.', 'Exploration', 5, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3016', 'Tanaris Bound', 'Visit Tanaris.', 'Exploration', 10, 'Interface\\Icons\\INV_Misc_Dust_02'),
  ('3017', 'Un''Goro Bound', 'Visit Un''Goro Crater.', 'Exploration', 10, 'Interface\\Icons\\INV_Misc_Head_Dragon_01'),
  ('3018', 'Winterspring Bound', 'Visit Winterspring.', 'Exploration', 10, 'Interface\\Icons\\Spell_Frost_FrostBolt02'),
  ('3019', 'Blasted Lands Bound', 'Visit the Blasted Lands.', 'Exploration', 10, 'Interface\\Icons\\Spell_Fire_Volcano'),
  ('3020', 'City Slicker: Stormwind', 'Visit Stormwind City.', 'Exploration', 5, 'Interface\\Icons\\Spell_Arcane_TeleportStormWind'),
  ('3021', 'City Slicker: Orgrimmar', 'Visit Orgrimmar.', 'Exploration', 5, 'Interface\\Icons\\Spell_Arcane_TeleportOrgrimmar'),
  ('3022', 'City Slicker: Ironforge', 'Visit Ironforge.', 'Exploration', 5, 'Interface\\Icons\\Spell_Arcane_TeleportIronForge'),
  ('3023', 'City Slicker: Undercity', 'Visit Undercity.', 'Exploration', 5, 'Interface\\Icons\\Spell_Arcane_TeleportUnderCity'),
  ('3024', 'City Slicker: Thunder Bluff', 'Visit Thunder Bluff.', 'Exploration', 5, 'Interface\\Icons\\Spell_Arcane_TeleportThunderBluff'),
  ('3025', 'City Slicker: Darnassus', 'Visit Darnassus.', 'Exploration', 5, 'Interface\\Icons\\Spell_Arcane_TeleportDarnassus'),
  ('3026', 'Eastern Kingdoms Sampler', 'Visit Elwynn Forest, Westfall, and Redridge Mountains.', 'Exploration', 15, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3027', 'Kalimdor Sampler', 'Visit Durotar, The Barrens, and Mulgore.', 'Exploration', 15, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3028', 'Blackrock Bound', 'Visit Burning Steppes or Searing Gorge.', 'Exploration', 10, 'Interface\\Icons\\Spell_Fire_Volcano'),
  ('3029', 'Hinterlands Bound', 'Visit The Hinterlands.', 'Exploration', 10, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('3030', 'Silithus Bound', 'Visit Silithus.', 'Exploration', 10, 'Interface\\Icons\\INV_Misc_Gem_Stone_01'),
  ('4001', 'First Blood', 'Slay your first creature.', 'Combat', 5, 'Interface\\Icons\\Ability_DualWield'),
  ('4002', 'Blooded', 'Slay 50 creatures.', 'Combat', 5, 'Interface\\Icons\\Ability_Warrior_SavageBlow'),
  ('4003', 'Exterminator', 'Slay 250 creatures.', 'Combat', 10, 'Interface\\Icons\\Ability_Warrior_Rampage'),
  ('4004', 'Grim Reaper', 'Slay 1,000 creatures.', 'Combat', 15, 'Interface\\Icons\\Spell_Shadow_DeathPact'),
  ('4005', 'Walking Apocalypse', 'Slay 5,000 creatures.', 'Combat', 25, 'Interface\\Icons\\Spell_Shadow_AnimateDead'),
  ('4006', 'Murloc Massacre', 'Slay 100 murlocs. Somebody has to do it.', 'Combat', 10, 'Interface\\Icons\\INV_Misc_MonsterHead_02'),
  ('4007', 'Gnoll Problem', 'Slay 50 gnolls.', 'Combat', 10, 'Interface\\Icons\\INV_Misc_Head_Gnoll_01'),
  ('4008', 'Kobold Clearance', 'Slay 50 kobolds. You no take candle!', 'Combat', 10, 'Interface\\Icons\\INV_Misc_Candle_02'),
  ('4009', 'Defias Buster', 'Slay 50 Defias.', 'Combat', 10, 'Interface\\Icons\\Ability_Rogue_Disguise'),
  ('4010', 'Scourge of the Scourge', 'Slay 100 undead (name contains "undead", "skeleton", "ghoul", or "zombie"). Slay 100 skeletons.', 'Combat', 10, 'Interface\\Icons\\Spell_Shadow_RaiseDead'),
  ('4011', 'Beast Master', 'Slay 100 beasts named wolf, bear, boar, or cat — specifically, slay 100 wolves.', 'Combat', 10, 'Interface\\Icons\\Ability_Hunter_RunningShot'),
  ('4012', 'Bear Necessities', 'Slay 50 bears.', 'Combat', 10, 'Interface\\Icons\\Ability_Hunter_RunningShot'),
  ('4013', 'Spider Smasher', 'Slay 75 spiders.', 'Combat', 10, 'Interface\\Icons\\Spell_Nature_Web'),
  ('4014', 'Raptors Ate My Neighbor', 'Slay 50 raptors.', 'Combat', 10, 'Interface\\Icons\\Ability_Hunter_RunningShot'),
  ('4015', 'Ogre Obliterator', 'Slay 40 ogres.', 'Combat', 10, 'Interface\\Icons\\Ability_Warrior_WarCry'),
  ('4016', 'Elemental Equilibrium', 'Slay 50 elementals.', 'Combat', 10, 'Interface\\Icons\\Spell_Fire_Fire'),
  ('4017', 'Dragonkin Dispatcher', 'Slay 30 dragonkin or whelps.', 'Combat', 15, 'Interface\\Icons\\INV_Misc_Head_Dragon_01'),
  ('4018', 'Crit Happens', 'Land 10 critical strikes.', 'Combat', 5, 'Interface\\Icons\\Ability_BackStab'),
  ('4019', 'Critical Mass', 'Land 100 critical strikes.', 'Combat', 10, 'Interface\\Icons\\Ability_BackStab'),
  ('4020', 'RNG Blesses You', 'Land 1,000 critical strikes.', 'Combat', 20, 'Interface\\Icons\\Ability_Warrior_SavageBlow'),
  ('4021', 'That Was Close', 'Survive combat after dropping to 10% health or lower.', 'Combat', 10, 'Interface\\Icons\\Spell_Holy_SealOfSacrifice'),
  ('4022', 'Near-Death Experience', 'Survive combat after dropping to 5% health or lower.', 'Combat', 15, 'Interface\\Icons\\Spell_Shadow_LifeDrain'),
  ('4023', 'One HP Wonder', 'Survive combat after dropping to 1% health or lower. Absolute cinema.', 'Combat', 25, 'Interface\\Icons\\Spell_Holy_SealOfProtection'),
  ('4024', 'Centurion', 'Slay 100 creatures.', 'Combat', 5, 'Interface\\Icons\\Ability_Warrior_OffensiveStance'),
  ('4025', 'Hog Wild', 'Slay 50 boars.', 'Combat', 5, 'Interface\\Icons\\INV_Misc_Food_60'),
  ('5001', 'Errand Boy', 'Complete your first quest.', 'Quests', 5, 'Interface\\Icons\\INV_Misc_Note_02'),
  ('5002', 'Helpful Hand', 'Complete 10 quests.', 'Quests', 5, 'Interface\\Icons\\INV_Misc_Note_01'),
  ('5003', 'Questing Machine', 'Complete 50 quests.', 'Quests', 10, 'Interface\\Icons\\INV_Misc_Note_03'),
  ('5004', 'Loremaster in Training', 'Complete 100 quests.', 'Quests', 10, 'Interface\\Icons\\INV_Misc_Book_09'),
  ('5005', 'Walking Encyclopedia', 'Complete 250 quests.', 'Quests', 15, 'Interface\\Icons\\INV_Misc_Book_11'),
  ('5006', 'Questaholic', 'Complete 500 quests.', 'Quests', 25, 'Interface\\Icons\\INV_Misc_Book_07'),
  ('5007', 'No Job Too Small', 'Complete 1,000 quests.', 'Quests', 50, 'Interface\\Icons\\INV_Misc_Book_13'),
  ('6001', 'Copper Pincher', 'Loot a total of 1 gold.', 'Wealth', 5, 'Interface\\Icons\\INV_Misc_Coin_05'),
  ('6002', 'Pocket Change', 'Loot a total of 10 gold.', 'Wealth', 5, 'Interface\\Icons\\INV_Misc_Coin_03'),
  ('6003', 'Comfortable Living', 'Loot a total of 100 gold.', 'Wealth', 10, 'Interface\\Icons\\INV_Misc_Coin_02'),
  ('6004', 'Fat Stacks', 'Loot a total of 500 gold.', 'Wealth', 15, 'Interface\\Icons\\INV_Misc_Coin_01'),
  ('6005', 'Gold Baron', 'Loot a total of 1,000 gold.', 'Wealth', 25, 'Interface\\Icons\\INV_Misc_Coin_15'),
  ('6006', 'AH Whale', 'Loot a total of 5,000 gold.', 'Wealth', 50, 'Interface\\Icons\\INV_Misc_Coin_17'),
  ('6007', 'Shiny!', 'Loot any item.', 'Wealth', 5, 'Interface\\Icons\\INV_Misc_Bag_05'),
  ('6008', 'Pack Rat', 'Loot 100 items.', 'Wealth', 10, 'Interface\\Icons\\INV_Misc_Bag_10'),
  ('6009', 'Hoarder', 'Loot 500 items.', 'Wealth', 15, 'Interface\\Icons\\INV_Misc_Bag_17'),
  ('6010', 'Linen Lord', 'Loot 20 items with "Linen" in the name.', 'Wealth', 5, 'Interface\\Icons\\INV_Fabric_Linen_01'),
  ('6011', 'Woolly Bully', 'Loot 20 items with "Wool" in the name.', 'Wealth', 5, 'Interface\\Icons\\INV_Fabric_Wool_01'),
  ('7001', 'Apprentice Gathering', 'Reach 50 Mining skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Mining'),
  ('7002', 'Journeyman Miner', 'Reach 150 Mining skill.', 'Professions', 10, 'Interface\\Icons\\Trade_Mining'),
  ('7003', 'Artisan Miner', 'Reach 225 Mining skill.', 'Professions', 15, 'Interface\\Icons\\INV_Pick_02'),
  ('7004', 'Master Miner', 'Reach 300 Mining skill.', 'Professions', 25, 'Interface\\Icons\\INV_Pick_03'),
  ('7005', 'Green Thumb', 'Reach 75 Herbalism skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Herbalism'),
  ('7006', 'Master Herbalist', 'Reach 300 Herbalism skill.', 'Professions', 25, 'Interface\\Icons\\INV_Misc_Herb_17'),
  ('7007', 'Thick Hide', 'Reach 75 Skinning skill.', 'Professions', 5, 'Interface\\Icons\\INV_Misc_Pelt_Wolf_01'),
  ('7008', 'Master Skinner', 'Reach 300 Skinning skill.', 'Professions', 25, 'Interface\\Icons\\INV_Misc_Pelt_Bear_03'),
  ('7009', 'Blacksmith''s Apprentice', 'Reach 75 Blacksmithing skill.', 'Professions', 5, 'Interface\\Icons\\Trade_BlackSmithing'),
  ('7010', 'Master Blacksmith', 'Reach 300 Blacksmithing skill.', 'Professions', 25, 'Interface\\Icons\\INV_Hammer_09'),
  ('7011', 'Tailor''s Apprentice', 'Reach 75 Tailoring skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Tailoring'),
  ('7012', 'Master Tailor', 'Reach 300 Tailoring skill.', 'Professions', 25, 'Interface\\Icons\\INV_Fabric_Silk_02'),
  ('7013', 'Leatherworker''s Apprentice', 'Reach 75 Leatherworking skill.', 'Professions', 5, 'Interface\\Icons\\INV_Misc_ArmorKit_17'),
  ('7014', 'Master Leatherworker', 'Reach 300 Leatherworking skill.', 'Professions', 25, 'Interface\\Icons\\INV_Misc_ArmorKit_17'),
  ('7015', 'Alchemist''s Apprentice', 'Reach 75 Alchemy skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Alchemy'),
  ('7016', 'Master Alchemist', 'Reach 300 Alchemy skill.', 'Professions', 25, 'Interface\\Icons\\INV_Potion_27'),
  ('7017', 'Engineer''s Apprentice', 'Reach 75 Engineering skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Engineering'),
  ('7018', 'Master Engineer', 'Reach 300 Engineering skill.', 'Professions', 25, 'Interface\\Icons\\INV_Gizmo_01'),
  ('7019', 'Enchanter''s Apprentice', 'Reach 75 Enchanting skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Engraving'),
  ('7020', 'Master Enchanter', 'Reach 300 Enchanting skill.', 'Professions', 25, 'Interface\\Icons\\INV_Enchant_DustArcane'),
  ('7021', 'First Aid Novice', 'Reach 75 First Aid skill.', 'Professions', 5, 'Interface\\Icons\\Spell_Holy_SealOfSacrifice'),
  ('7022', 'Field Medic', 'Reach 300 First Aid skill.', 'Professions', 15, 'Interface\\Icons\\INV_Misc_Bandage_12'),
  ('7023', 'Cooking Novice', 'Reach 75 Cooking skill.', 'Professions', 5, 'Interface\\Icons\\INV_Misc_Food_15'),
  ('7024', 'Chef de Cuisine', 'Reach 300 Cooking skill.', 'Professions', 15, 'Interface\\Icons\\INV_Misc_Food_64'),
  ('7025', 'Angler''s Apprentice', 'Reach 75 Fishing skill.', 'Professions', 5, 'Interface\\Icons\\Trade_Fishing'),
  ('7026', 'Old Salt', 'Reach 300 Fishing skill.', 'Professions', 15, 'Interface\\Icons\\INV_Misc_Fish_02'),
  ('8001', 'Dungeon Delver', 'Enter any dungeon or raid.', 'Dungeons', 5, 'Interface\\Icons\\INV_Misc_Key_11'),
  ('8002', 'Instance Hopper', 'Enter 5 different dungeons or raids.', 'Dungeons', 10, 'Interface\\Icons\\INV_Misc_Key_11'),
  ('8003', 'Keyring Collector', 'Enter 10 different dungeons or raids.', 'Dungeons', 20, 'Interface\\Icons\\INV_Misc_Key_08'),
  ('8004', 'Dead Mines, Live Heroes', 'Enter The Deadmines.', 'Dungeons', 10, 'Interface\\Icons\\Ability_Rogue_Disguise'),
  ('8005', 'Wailing in the Depths', 'Enter Wailing Caverns.', 'Dungeons', 10, 'Interface\\Icons\\Spell_Nature_Acid_01'),
  ('8006', 'Shadowfang Sojourn', 'Enter Shadowfang Keep.', 'Dungeons', 10, 'Interface\\Icons\\Spell_Shadow_ShadowBolt'),
  ('8007', 'Stockade Stint', 'Enter The Stockade.', 'Dungeons', 10, 'Interface\\Icons\\Spell_Shadow_SummonVoidWalker'),
  ('8008', 'Razorfen Run', 'Enter Razorfen Kraul or Razorfen Downs.', 'Dungeons', 10, 'Interface\\Icons\\Spell_Frost_FrostBolt02'),
  ('8009', 'Gnomeregan Infiltration', 'Enter Gnomeregan.', 'Dungeons', 10, 'Interface\\Icons\\INV_Gizmo_01'),
  ('8010', 'Scarlet Letter', 'Enter a Scarlet Monastery wing.', 'Dungeons', 10, 'Interface\\Icons\\Spell_Holy_PrayerOfHealing'),
  ('8011', 'Uldaman Unearthed', 'Enter Uldaman.', 'Dungeons', 10, 'Interface\\Icons\\INV_Pick_03'),
  ('8012', 'Zul''Farrak Vacation', 'Enter Zul''Farrak.', 'Dungeons', 10, 'Interface\\Icons\\INV_Misc_Head_Troll_01'),
  ('8013', 'Maraudon Mayhem', 'Enter Maraudon.', 'Dungeons', 10, 'Interface\\Icons\\Spell_Nature_Earthquake'),
  ('8014', 'Temple of Atal''Hakkar', 'Enter the Sunken Temple.', 'Dungeons', 15, 'Interface\\Icons\\INV_Misc_Head_Dragon_Green'),
  ('8015', 'Blackrock Depths', 'Enter Blackrock Depths.', 'Dungeons', 15, 'Interface\\Icons\\INV_Misc_Head_Dragon_Black'),
  ('8016', 'Lower Blackrock Spire', 'Enter Lower Blackrock Spire.', 'Dungeons', 15, 'Interface\\Icons\\INV_Misc_Head_Dragon_01'),
  ('8017', 'Stratholme Bound', 'Enter Stratholme.', 'Dungeons', 15, 'Interface\\Icons\\Spell_Shadow_DeathCoil'),
  ('8018', 'Scholomance Bound', 'Enter Scholomance.', 'Dungeons', 15, 'Interface\\Icons\\Spell_Frost_IceStorm'),
  ('8019', 'Onyxia''s Lair', 'Enter Onyxia''s Lair.', 'Dungeons', 25, 'Interface\\Icons\\INV_Misc_Head_Dragon_01'),
  ('8020', 'Molten Core Bound', 'Enter Molten Core.', 'Dungeons', 25, 'Interface\\Icons\\Spell_Fire_Fire'),
  ('8021', 'Blackwing Lair Bound', 'Enter Blackwing Lair.', 'Dungeons', 25, 'Interface\\Icons\\INV_Misc_Head_Dragon_Black'),
  ('8022', 'Ahn''Qiraj Bound', 'Enter the Temple of Ahn''Qiraj or Ruins of Ahn''Qiraj.', 'Dungeons', 25, 'Interface\\Icons\\Spell_Shadow_ShadowWordPain'),
  ('8023', 'Naxxramas Bound', 'Enter Naxxramas.', 'Dungeons', 25, 'Interface\\Icons\\Spell_Shadow_RaiseDead'),
  ('8024', 'VanCleef Vanquished', 'Slay Edwin VanCleef.', 'Dungeons', 15, 'Interface\\Icons\\Ability_Rogue_Disguise'),
  ('8025', 'Mutanus Muted', 'Slay Mutanus the Devourer.', 'Dungeons', 15, 'Interface\\Icons\\Spell_Nature_Acid_01'),
  ('9001', 'Did Somebody Say...?', 'Reach level 60. The world is yours.', 'Feats of Strength', 0, 'Interface\\Icons\\Spell_Holy_SummonChampion'),
  ('9002', 'Undying Legend', 'Reach level 60 without ever dying. A true Hardcore legend.', 'Feats of Strength', 0, 'Interface\\Icons\\Spell_Holy_HolyBolt'),
  ('9003', 'Millionaire', 'Loot a total of 10,000 gold.', 'Feats of Strength', 0, 'Interface\\Icons\\INV_Misc_Coin_17'),
  ('9004', 'Genocide Adjacent', 'Slay 10,000 creatures.', 'Feats of Strength', 0, 'Interface\\Icons\\Spell_Shadow_DeathPact'),
  ('9005', 'The Real Loremaster', 'Complete 2,000 quests.', 'Feats of Strength', 0, 'Interface\\Icons\\INV_Misc_Book_13'),
  ('9006', 'World Traveler', 'Visit 50 different zones.', 'Feats of Strength', 0, 'Interface\\Icons\\INV_Misc_Map_01'),
  ('9007', 'Key to the Kingdom', 'Enter 20 different dungeons or raids.', 'Feats of Strength', 0, 'Interface\\Icons\\INV_Misc_Key_07'),
  ('9008', 'Grandmaster of Everything', 'Earn 150 achievements.', 'Feats of Strength', 0, 'Interface\\Icons\\INV_Jewelry_Talisman_08'),
  ('10001', 'Duelist', 'Win a duel.', 'Player vs Player', 5, 'Interface\\Icons\\Ability_DualWield'),
  ('10002', 'Sparring Partner', 'Win 5 duels.', 'Player vs Player', 10, 'Interface\\Icons\\Ability_Warrior_Revenge'),
  ('10003', 'Arena Warmup', 'Win 25 duels.', 'Player vs Player', 15, 'Interface\\Icons\\Ability_Warrior_Revenge'),
  ('10004', 'Duel Master', 'Win 100 duels.', 'Player vs Player', 25, 'Interface\\Icons\\Ability_Warrior_DecisiveStrike')
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  points = excluded.points,
  icon = excluded.icon;
